baseURL = "https://kukuchen.com/"
languageCode = "en-us"
title = "KusHome"
theme = "ivy"
disqusShortname = "Ku"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:year/:month/:slug/"
  newsletter = "/newsletter/:year/:month/:slug/"

[menu]
  [[menu.main]]
  name="Reading"
  url="/books/"
  weight="1"

  [[menu.main]]
  name="BookList"
  url="/bibliography/"
  weight="2"

  [[menu.main]]
  name="Writing"
  url="/posts/"
  weight="3"
  
  [[menu.main]]
  name="Letter"
  url="/newsletter/"
  weight="4"

[params]
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."
  footer = "&copy; [Ku](https://kukuchen.com) | since 2009"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1